### ISSUE TITLE
7 lapos kiválasztás

### ISSUE THREAD

**Issue by kikeee95** [kikeee95/Poker#4]
public static int sevenCardEvaluator(Hand hand, ArrayList<Card> boardCards){

        int cardCount = 5;
        int combinationStrenght = 0;
        int temp;

        //Brute force megközelítés, végignézzük az összes lehetséges 7 lapos kombinációt és visszaadjuk a legerősebbet

        ArrayList<Card> combinations = new ArrayList<>();
        ArrayList<Card> combination = new ArrayList<>();
        ArrayList<Card> excluded = new ArrayList<>();

        for(int i = 0; i < hand.getCards().length; i++){
            combinations.add(hand.getCards()[i]);
        }

        for(int i = 0; i < boardCards.size(); i++){
            combinations.add(boardCards.get(i));
        }

        //7ből úgy tudunk 5 lapot kiválasztani, hogy kettőt mindig kihagyunk, 21 féle képpen választhatunk ki 2 lapot amit kihagyunk, ezt 2 ciklussal lehet kiválogatni

        for(int i = 0; i < combinations.size() - 1; i++){
            for(int j = i + 1; j < combinations.size(); j++){
                excluded.add(combinations.get(i));
                excluded.add(combinations.get(j));

                //kombináció létrehozása és kiértékelése a két kimaradó  lap nélkül
                if(excluded.size() == 2){
                   combination.addAll(combinations);

                   for(int k = 0; k < excluded.size(); k++){
                       combination.remove(excluded.get(k));
                   }
                   excluded.clear();
                }
                temp = new HandCombination(combination).getCombinationStrength();

                if(temp >= combinationStrenght){
                    combinationStrenght = temp;
                }

                combination.clear();

            }
        }
        return combinationStrenght;
    }

Ma főleg ezzel szenvedtem, a lényege az hogy ugye 7 lapból kell kiválasztani a legerősebb 5 lapos kombinációt, én ezzel a megoldással oldottam meg végül, teszteltem és jól is működik :D

**Comment by JNAttila** [comment]
A dupla FOR cikluson belül még egy FOR ciklus nem a legelegánsabb megoldás, de ebben az esetben szerintem ettől el tekinthetünk. Ránézésre és végig gondolva jól működik, illetve ha a tesztelés alapján is jól működik, ahogy írtad, nem érdemes egyszerűsíteni. Szerintem jó lesz így.
