### ISSUE TITLE
Multithread

### ISSUE THREAD

**Issue by kikeee95** [kikeee95/Poker#5]
A multithreading-el kapcsolatban lenne főleg kérdésem. Most meg kell írnom azt a részt, ahol egy adott függvény bekéri a mi lapjainkat, és a játékban lévő ellenfeleink ranget. Ez egy double értéket fog visszaadni. Ezt úgy fogom megoldani, ha teszem azt épp flop van, akkor van ugye 3 lap lent eddig.

Ahhoz még a deck dealcard() véletlenszerűen fog még 2 lapot generálni (**_k1_**) így jön ki az 5 lap, a dealcard() figyel arra, hogy ha előtte kiveszem a deckből a már bent lévő lapokat ne tudjon olyan lapot generálni ami egy játékosnál már van (**_r1_**).

Így meg van az 5 lap az asztalon, meg a mi 2 lapunk. Ekkor a még játékban lévő játékosok rangeből is randomolok mindenkinek egy lapot, majd a mi 2 lapunk, meg minden játékosnak a két randomolt lapját + a board 5 lapját külön-külön a sevenCardEvaluator() segítségével megnézem, majd ezeket összehasonlítva a sajátommal eldöntöm hogy azt a generált kimenetelt én nyerem-e vagy valamelyik AI játékos (**_r2_**).

Két változó fog kelleni, a generált leosztások száma, és hogy hány esetben nyernek az én lapjaim. Ezeket egymással osztva kapnám meg a nyerési esélyemet, azt adná a függvény vissza.

A probléma az hogy legalább 1 millió ilyen generált leosztás kéne egy normális eredményhez. Ez viszont biztosan nem lesz gyors (**_k2_**), pláne ha épp mondjuk 6 játékos is játékban van, bár az elég ritka de megeshet.

Nos a kérdés az, ha indítok 4 szálat (**_r3_**), ahol mind a négy szál végigcsinálná 250ezerszer ezt a műveletet, hogy generál 2 lapot a boardra, minden ellenfél kezébe lapokat, majd kiértékelve ezeket a győztest az egy jó ötletnek tűnik (**_r4_**). Ha esetleg tudnál erre megfelelő dolgot az hasznos lenne, lehet először csak megírom szimplán, aztán megnézem 1 milliót mennyi idő alatt számol és az alapján tudsz segíteni vmi megoldással (**_r5_**).

A kérdés hogy ha a fgv elején lesz egy változó int simulatedRound, int numberOfWins
Ez alatt pedig külön 4 négy szál. Akkor a négy szál kiszámolja a maga 250ezer leosztását, és nekik is van ez a két változó, ők elérik-e a threaden kívül lévőt (**_r6_**), vagy hogy tudom az eredményeiket összegezni?

**Comment by JNAttila** [comment]
Vannak kérdéseim (**_kX_**) és reakcióim (**_rX_**):
- **_k1_**: az asztalon lévő lapok mellé mindig annyi lapot generálsz, hogy 5 lap legyen a számításokban az asztalon? Így fogod tudni minden estben használni a 7 lapos kiértékelőt, ha jól értem.
- **_r1_**: ez egy logikus működés. Jó, hogy erre odafigyeltél! LIKE! :)
- **_r2_**: itt egy kicsit nem tudtam követni, hogy hogy is vannak a lapok generálva, de majd megbeszéljük.
- **_k2_**: az ~1 millió eset mennyire közelítés? Kellene-e mind az 1 millió esetet végig számolni, vagy csak random az ötödrésze is elég volna? Járható út volna-e, ha lenne egy olyan lap halmaz (mínusz ami valamelyik játékosnál megtalálható), amivel végigszámolnád ezeket az eseteket a becsléshez?
- **_r3_**: a 4 szál valami valós korlát, vagy csak nem szeretnéd nagyon szabadjára engedni a számolást? Én rábíznám a rendszerre, hogy futtassa annyi szálon, amennyin akarja és/vagy elbírja.
- **_r4_**: első olvasatra jó ötletnek tűnik, de valahogy vágni kellene, ha lehetséges, a megvizsgálandó esetek teréből.
- **_r5_**: utánanézek és készítek valami demó kódot erre. Ha Te is kísérletezel ezzel a résszel, használj időmérést a teljes számolásra (a rész-számításokra szerintem nem szükséges), hogy melyik megvalósítás mennyire gyors. Esetleg egy konfigurációs paraméterrel lehessen szabályozni, hogy melyik megvalósítás működjön. Így tovább fejleszthető bármelyik ötlet és könnyen összemérhetőek újra.
- **_r6_**: a párhuzamosan futó szálak esetén megoldható, hogy elérjenek közös változókat, de az gond, hogy ezeket majd nem csak ellenőrizni, de frissíteni is szeretnék az egyes szálak. Így meg kell oldani, hogy a közös változót egy időben csak egy szál írhassa. Ez szerintem rontja a párhuzamosságot, különösen, ha 1 millió számítást kellene elvégezni. Azt gondoltam erre, hogy a kiszámítandó változókat és listákat egységbe kellene zárni az eredménnyel. Amikor az összes szál befejezte a munkát, akkor végig nézni az összes eredményt és megkeresni a legjobbat. Ez egy megközelítés, aminek a megvalósításában tudok segíteni. Viszont lehet, hogy az eredmény párhuzamos ellenőrzése és frissítése a jobb. Jó lenne kipróbálni mind a kettőt. Egyébként elképzelhetőnek tartom, hogy egy i3-as laptopon nem az a megvalósítás lenne a legjobb, mint egy i5-ös vagy i7-es asztali gépen. Ki kell próbálni.

**Comment by kikeee95** [comment]
Közben elkészült amit írtam, PlayerPlayed osztályon belül van, utolsó kettő. Az equityInnerCalculation(), az ami megmondja hogy épp nyerő-e a szimulált leosztás végén a kezünk vagy sem. az equity() pedig lényegében ezt futtatja le, jelen esetben 25ezer alkalommal. Teszteltem 2 különböző range-el rendelkező játékos ellen, az egyik játékosé elég nagy is volt ráadásul. Az equilab equity kalkulátorához 2%-os eltérésen belül van az amit az enyém ad vissza, általában kevesebb mint 1% az eltérés a kettő között. Ez bőven nagyon jó eredmény, így teljesen randomolt kártyák esetén. Azt néztem ha lefuttatom 100ezer alkalommal sincs sokkal jobb eredmény, mint 25ezer esetén. Kérdés hogy ezt a 25ezret milyen módon lehetne gyorsítani? Mert ugye jelenleg egy for(0->25000) van benne.
