### ISSUE TITLE
Beüzemelési leírás

### ISSUE THREAD

**Issue by JNAttila** [kikeee95/Poker#8]
Kell egy leírás az alábbiakkal:
- milyen telepített komponensek kellenek
- milyen fejlesztőeszközt használtál
- hogyan nyisd meg a kódot a fejlesztőeszközzel és hogyan tudod futtatni

**Comment by kikeee95** [comment]
https://www.poker-genius.com/download.php

Innen tudod letölteni.
Product key-t elküldtem emailben hozzá.

Ring games -> Full Ring XenBots asztalt nyissad meg, stakes mind1 igazából, de inkább az alacsonyakat mert az a tuti, 0.05/0.10

Options -> 4 color deck pipa
Options -> auto deal pipa
Options/Window options: Always full mode, Color scheme: Light Grey

![image](https://user-images.githubusercontent.com/18285151/56869810-e15f2300-6a05-11e9-8b95-9e23935a920f.png)

Jobb sarokban ülő embert szedd ki, mert 9 játékosos játékot szimuláljuk. Azzal nem foglalkozok.

**Comment by kikeee95** [comment]
IntelliJ, ezek az external libraryk:

![image](https://user-images.githubusercontent.com/18285151/56869833-39962500-6a06-11e9-9b39-d0040cfe96b3.png)

Tess4J 4.3.1

https://jar-download.com/artifacts/net.sourceforge.tess4j/tess4j/4.3.1/source-code

Általam használt Tesseract mappa:
https://drive.google.com/open?id=132j_shSULLzYFridLcwgooyfQMHCvaAa
