### ISSUE TITLE
Hand-history formázó

### ISSUE THREAD

**Issue by JNAttila** [kikeee95/Poker#9]
Egyik formátumról a másik formátumra konvertáló külső alkalmazás fejlesztése.

**Comment by JNAttila** [comment]
Kellenek a fájlok, hogy miről mire menjen a konvertálás.

**Comment by kikeee95** [comment]
Pokerstars handhistoryk:
http://hhsender.com/download/purchase/?file=THNL_PS_10_FR_100K_28-04-2019_5cc537e94cfb43_86667139.zip

PokerGenius history:
https://drive.google.com/file/d/1QUgq2jCucjIl9UMAe6VTSFBCDATTgmRn/view

PokerGenius historyt kell átalakítani PokerStars mintára
